### ISSUE TITLE
Debounce search box input

### ISSUE THREAD

**Issue by lencioni** [tdooner/mosaic#12]
Searching can feel slow because it is trying to search and update the UI for every character entered. Debouncing the input should make things feel quite a bit smoother.

**Comment by tdooner** [comment]
A combination of debouncing and the `shouldComponentUpdate` logic improves the performance dramatically. (Try it and tell me what you think.) Thanks for the suggestion.

**Comment by tdooner** [comment]
...I actually find it fun to just search for random things because it is so fast to do so....
