### ISSUE TITLE
Some Sketch files render poorly

### ISSUE THREAD

**Issue by tdooner** [tdooner/mosaic#4]
e.g. our Partner Tools mocks -- some fonts are mis-sized causing a lot of text to wrap. It's possible that the proper font just isn't installed on the machine we run this on, but I installed all the fonts I could find, so I'm also skeptical of this explanation.

**Comment by lencioni** [comment]
If you are working with Roboto, there are different versions and it is important that you install the correct versions. You should be able to get the right fonts for the Brigade Sketch files in our dropbox Design > General > Fonts.

**Comment by tdooner** [comment]
@lencioni: @rf- helped me track this down to the installation of both Roboto 1.2 and Roboto 2.0, and sketch accidentally using the wrong one when rendering. I verified that a couple slices that previously were broken now render properly. I'm going to close this and reopen if new slices have rendering problems.

**Comment by tdooner** [comment]
(I had to uninstall Roboto 1.2)
